#pragma once

#include <string>

#include <SDL2/SDL_pixels.h> // SDL_Color

#include "ui/element/ui_element.hpp"

// Forward declaration of TextureController is in ui/element/ui_element.hpp

class UiTextElement : public UiElement
{
    private:
        std::string m_text;
        
        SDL_Color m_textColor;
        // Texture that is generated by a UiTextElement is in TextureController::m_textures
        FontSize m_fontSize;
        int m_maxWidth;

    public:
        UiTextElement(TextureController& textureController, const UiKey& key, 
            const SDL_Color color=SDL_Color{0,0,0,255});

        void SetText(const std::string& text);
        void SetTextSize(const FontSize size);
        void GenerateText();
        void SetMaxWidth(const float amount);

        void ComputeFinal() override;
};