#pragma once

#include "drawable.hpp"

enum class Axis
{
    Width, Height // Should add Both ?
};

enum class Anchor
{
    Left, Right, Center, Top, Bottom
};

class UiElement : public ScreenDrawable
{
    protected:
        std::vector<UiElement*> m_childs;
        ScreenPosition m_localPosition; // In addition to ScreenDrawable::m_position, UiElement have a relative position to its parent
        AreaSize m_parentSize;
        // For the root UiElement, local = global
        // For every other UiElement B, child of A, we have : global position (B) = global position (A) + local position (B)  

    public:
        UiElement(TextureController& textureController, const std::string& textureFilepath, const ScreenPosition localPosition={0,0});
        UiElement(TextureController& textureController, const ScreenPosition localPosition={0,0});
        
        void SetParentSize(const AreaSize parentSize);
        void AddChild(UiElement* child); // Warning : AddChild must be used only once UiElement configuration has been done
        void ComputeZoom(const float scale, const Axis axis); // scale in [0, +inf] (Do not use for TextArea)
        void ComputePosition(const Anchor xAnchor, const Anchor yAnchor); // Must be called after ComputeZoom
        void AddPadding(const Axis sourceAxis, const Axis paddingAxis, const float scale);
        void AddPadding(const Axis paddingAxis, const float scale);
        void DrawTexture() const override; 
        void UpdatePosition(const ScreenPosition parentPosition={0,0}); // Update position on current UiElement and each children
        void SetLocalPosition(const ScreenPosition localPosition); // To move a UiElement, use this function, and not ScreenDrawable::SetScreenPosition()
        void AddLocalPosition(const ScreenPosition padding);
};

class TextArea : public UiElement
{
    private:
        // TTF_Font in TextArea < UiElement < ScreenDrawable < Drawable (TextureController has a Map<TextureKey,TTF_Font)
        SDL_Color m_textColor;
        // Texture that is generated by a TextArea is in TextureController::m_textures
        TextureKey m_fontKey;
        int m_maxWidth;

    public:
        TextArea(TextureController& textureController, const std::string& fontFilepath, const SDL_Color color=SDL_Color{0,0,0,255});
        void SetText(const std::string& text);
        void SetMaxWidth(const float scale);
};

class UiController
{
    protected:
        UiElement* m_root; // Root will be a rendered UiElement, not just abstract
        void SetRoot(UiElement* ui_root, const AreaSize initialSize); // Because the root has no parent, we must specified its initial size

    public:
        void Draw() const;
};

// UI configuration will not stay in constructor

class GameplayUiController : public UiController
{
    private:
        UiElement m_dialogBox;
        UiElement m_faceset;
        UiElement m_face;
        TextArea m_textArea;

    public:
        GameplayUiController(TextureController& textureController, const Camera& camera, const std::string& fontFilepath);
};

class EditorUiController : public UiController
{
    private:
        UiElement m_dialogBox;
        TextArea m_textArea;
        int m_lastLayer; // Should create EditorEventState struct, and have a parameter in UiController::Draw or EditorUiController::UpdateState ?
        // GameplayUiController will also need a (Gameplay)EventState 

    public:
        EditorUiController(TextureController& textureController, const Camera& camera, const std::string& fontFilepath, const int selectedLayer);
        void UpdateState(const int selectedLayer); // Could use EditorEventState, and call UpdateState (private) in UiController::Draw ?
};

class BattleUiController : public UiController
{
    private:
        // Will be removed
        UiElement m_background;
        UiElement m_player;
        UiElement m_enemy;
        UiElement m_playerBox;
        UiElement m_enemyBox;
        TextArea m_playerInfo;
        TextArea m_enemyInfo;
        UiElement m_mainBox;

    public:
        BattleUiController(TextureController& textureController, const Camera& camera, const std::string& fontFilepath);
};