#pragma once

#include <memory>
#include <stdexcept>
#include <string>

#include "drawable.hpp"

enum class Axis
{
    Width, Height // Should add Both ?
};

enum class Anchor
{
    Left, Right, Center, Top, Bottom
};

class UiElement : public ScreenDrawable
{
    protected:
        std::vector<std::unique_ptr<UiElement>> m_childs;
        ScreenPosition m_localPosition; // In addition to ScreenDrawable::m_position, UiElement have a relative position to its parent
        AreaSize m_parentSize;
        // For the root UiElement, local = global
        // For every other UiElement B, child of A, we have : global position (B) = global position (A) + local position (B)  

        void AddChild(std::unique_ptr<UiElement>& child); // Do not use directly AddChild, use instead BuildChild

    public:
        UiElement(TextureController& textureController, const std::string& textureFilepath, const ScreenPosition localPosition={0,0});
        UiElement(TextureController& textureController, const ScreenPosition localPosition={0,0});
        
        virtual void ComputeFinal(
            const float scale, const Axis zoomAxis, // ComputeZoom
            const Anchor xAnchor, const Anchor yAnchor, // ComputePosition
            const float paddingScale, const Axis sourceAxis, const Axis paddingAxis);

        // Warning : BuildChild must be used only once configuration of the current calling object has been done
        void BuildChild(std::unique_ptr<UiElement> child,
            const float zoomScale, const Axis zoomAxis, // ComputeZoom
            const Anchor xAnchor, const Anchor yAnchor, // ComputePosition
            const float paddingScale, const Axis sourceAxis, const Axis paddingAxis); // AddPadding

        void SetParentSize(const AreaSize parentSize);
        void ComputeZoom(const float scale, const Axis axis); // scale in [0, +inf] (Do not use for TextArea)
        void ComputePosition(const Anchor xAnchor, const Anchor yAnchor); // Must be called after ComputeZoom
        void AddPadding(const float scale, const Axis sourceAxis, const Axis paddingAxis);
        void AddPadding(const float scale, const Axis paddingAxis); // Remove
        void DrawTexture() const override; 
        void UpdatePosition(const ScreenPosition parentPosition={0,0}); // Update position on current UiElement and each children
        void SetLocalPosition(const ScreenPosition localPosition); // To move a UiElement, use this function, and not ScreenDrawable::SetScreenPosition()
        void AddLocalPosition(const ScreenPosition padding);
};

class TextArea : public UiElement
{
    private:
        std::string m_text;
        // TTF_Font in TextArea < UiElement < ScreenDrawable < Drawable (TextureController has a Map<TextureKey,TTF_Font)
        SDL_Color m_textColor;
        // Texture that is generated by a TextArea is in TextureController::m_textures
        TextureKey m_fontKey;
        int m_maxWidth;

    public:
        TextArea(TextureController& textureController, const std::string& fontFilepath, const SDL_Color color=SDL_Color{0,0,0,255});
        
        void SetText(const std::string& text); // Must be called before GenerateText
        void GenerateText();
        void SetMaxWidth(const float scale);

        void ComputeFinal(
            const float zoomScale, const Axis zoomAxis, // ComputeZoom
            const Anchor xAnchor, const Anchor yAnchor, // ComputePosition
            const float paddingScale, const Axis sourceAxis, const Axis paddingAxis)
        override;
};