#pragma once

#include "drawable.hpp"

class UiElement : public ScreenDrawable
{
    private:
        std::vector<UiElement*> m_childs;
        ScreenPosition m_local_position; // In addition to ScreenDrawable::m_position, UiElement have a relative position to its parent
        // For the root UiElement, local = global
        // For every other UiElement B, child of A, we have : global position (B) = global position (A) + local position (B)  

    public:
        UiElement(TextureController& texture_controller, const std::string& texture_filepath, const ScreenPosition local_position={0,0});
        UiElement(TextureController& texture_controller, const ScreenPosition local_position={0,0});

        void AddChild(UiElement* child);
        void DrawTexture() const override; 
        void UpdatePosition(const ScreenPosition parent_position={0,0}); // Update position on current UiElement and each children
        void SetLocalPosition(const ScreenPosition local_position); // To move a UiElement, use this function, and not ScreenDrawable::SetScreenPosition()
};

class TextArea : public UiElement
{
    private:
        // TTF_Font in TextArea < UiElement < ScreenDrawable < Drawable (TextureController has a Map<TextureKey,TTF_Font)
        SDL_Color m_text_color;
        // Texture that is generated by a TextArea is in TextureController::m_textures
        TextureKey m_font_key;

    public:
        TextArea(TextureController& texture_controller, const std::string& font_filepath, const SDL_Color color=SDL_Color{0,0,0,255});
        void SetText(const std::string& text, const int max_width);
};

class UiController
{
    protected:
        const UiElement* m_root; // Root will be a rendered UiElement, not just abstract 

    public:
        void Draw() const;
};

class GameplayUiController : public UiController
{
    private:
        UiElement m_dialog_box;
        TextArea m_text_area;

    public:
        GameplayUiController(TextureController& texture_controller, const Camera& camera, const std::string& font_filepath);
};