#pragma once

#include <memory>
#include <stdexcept>
#include <string>

#include "image/drawable.hpp"
#include "system/notifier.hpp"

using ElementKey = std::string; // ???

enum class UiElementEvent
{
    Delete // Create ?
};

enum class Axis
{
    Width, Height, None
};

enum class Anchor
{
    LeftIn, LeftOut, 
    RightIn, RightOut,
    Center,
    TopIn, TopOut,
    BottomIn, BottomOut
};

template<typename T>
struct UiValue
{
    ElementKey id; // const ?
    T value;

    UiValue(ElementKey key, T v):
        id(key), value(v) 
    {}
};

struct UiParams // Should not be here ?
{
    float scale;
    Axis scaleAxis; // TextArea don't use this value (text size is handled by the font, the scale value is used for SetMaxWidth())
    Anchor xAnchor;
    Anchor yAnchor;
    float xPadding;
    float yPadding;

    UiParams() {
        scale = 1.f;
        scaleAxis = Axis::None;
        xAnchor = Anchor::Center;
        yAnchor = Anchor::Center;
        xPadding = 0.f;
        yPadding = 0.f;
    }
};

class UiElement : public ScreenDrawable, public Notifier<UiElementEvent>
{
    private:
        const ElementKey m_key;
        
    protected:
        std::vector<std::unique_ptr<UiElement>> m_childs;
        
        ScreenPosition m_localPosition; // In addition to ScreenDrawable::m_position, UiElement have a relative position to its parent
        // For the root UiElement, local = global
        // For every other UiElement B, child of A, we have : global position (B) = global position (A) + local position (B)  
        
        // UiElement const* m_parent; 
        UiElement* m_parent; 
        // Because UiElement can be subroot (without real parent, only UiController), I can't use UiElement::GetPosition() and GetSize()
        // That's why I still need parentPosition and parentSize members
        ScreenPosition m_parentPosition;
        AreaSize m_parentSize;

        UiParams m_params;

    public:
        UiElement(TextureController& textureController, const ElementKey& key,
            const std::string& textureFilepath, const ScreenPosition localPosition={0,0});
        UiElement(TextureController& textureController, const ElementKey& key, 
            const ScreenPosition localPosition={0,0});
        virtual ~UiElement();
        
        virtual void ComputeFinal();
        
        std::vector<std::unique_ptr<UiElement>>& GetChilds(); // Should return a const vector ? The function should be const ?
        std::unique_ptr<UiElement> RemoveChild(const ElementKey& key);
        UiElement* GetParent(); // Should return const and be const ?
        const ElementKey& GetKey() const;
        UiParams& GetParams();

        void AddChild(std::unique_ptr<UiElement>& child);
        // Warning : BuildChild must be used only once configuration of the current calling object has been done
        void BuildChild(std::unique_ptr<UiElement> child);

        // void SetParent(UiElement const* parent);
        void SetParent(UiElement* parent);
        void SetParentSize(const AreaSize parentSize);
        void SetParentPosition(const ScreenPosition parentPosition);
        void SetParamsScale(const float scale);
        void ComputeZoom(const float scale, const Axis axis); // scale in [0, +inf]
        void ComputePosition(const Anchor xAnchor, const Anchor yAnchor); // Must be called after ComputeZoom
        void SetPadding(const float xPadding, const float yPadding);
        void DrawTexture() const override; 
        void UpdatePosition(); // Update position on current UiElement and each children
        void SetLocalPosition(const ScreenPosition localPosition); // To move a UiElement, use this function, and not ScreenDrawable::SetScreenPosition()
        void AddLocalPosition(const ScreenPosition padding);
};

class TextArea : public UiElement
{
    private:
        std::string m_text;
        // TTF_Font in TextArea < UiElement < ScreenDrawable < Drawable (TextureController has a Map<TextureKey,TTF_Font)
        SDL_Color m_textColor;
        // Texture that is generated by a TextArea is in TextureController::m_textures
        TextureKey m_fontKey;
        int m_maxWidth;

    public:
        TextArea(TextureController& textureController, const ElementKey& key, 
            const std::string& fontFilepath, const SDL_Color color=SDL_Color{0,0,0,255});
        // ~TextArea();

        void SetText(const std::string& text);
        void GenerateText();
        void SetMaxWidth(const float amount);

        void ComputeFinal() override;
};