#pragma once

#include <memory>
#include <string>

#include <SDL2/SDL_pixels.h> // SDL_Color

#include "image/drawable.hpp"
#include "image/image_types.hpp" // ScreenPosition
#include "core/notifier.hpp"
#include "ui/ui_types.hpp" // UiKey

class FontController;
class TextureController;

class UiElement : public ScreenDrawable, public Notifier<UiElementEvent>
{
    private:
        UiKey m_key; // Could be const if I removed UiController::UpdateKey(), but I need it for ui template instanciation
        
    protected:
        std::vector<std::unique_ptr<UiElement>> m_childs;
        
        ScreenPosition m_localPosition; // In addition to ScreenDrawable::m_position, UiElement have a relative position to its parent
        // For the root UiElement, local = global
        // For every other UiElement B, child of A, we have : global position (B) = global position (A) + local position (B)  
        
        // UiElement const* m_parent; 
        UiElement* m_parent; 
        // Because UiElement can be subroot (without real parent, only UiController), I can't use UiElement::GetPosition() and GetSize()
        // That's why I still need parentPosition and parentSize members
        ScreenPosition m_parentPosition;
        AreaSize m_parentSize;

        UiParams m_params;

    public:
        UiElement(TextureController& textureController, const UiKey& key,
            const std::string& textureFilepath, const ScreenPosition localPosition={0,0});
        UiElement(TextureController& textureController, const UiKey& key, 
            const ScreenPosition localPosition={0,0});
        virtual ~UiElement();
        
        virtual void ComputeFinal();
        
        std::unique_ptr<UiElement> RemoveChild(const UiKey& key);
        UiElement* GetParent(); // Should return const and be const ?
        const UiKey& GetKey() const;
        UiParams& GetParams();

        void AddChild(std::unique_ptr<UiElement>& child);
        // Warning : BuildChild must be used only once configuration of the current calling object has been done
        void BuildChild(std::unique_ptr<UiElement> child);

        void SetKey(const UiKey& key); // Do not use directly (UiController::UpdateKey)
        void SetParent(UiElement* parent);
        void SetParentSize(const AreaSize parentSize);
        void SetParentPosition(const ScreenPosition parentPosition);
        void SetParams(const UiParams& params);
        void SetParamsScale(const float scale);
        void SetParamsPadding(const Axis axis, const float value);
        
        void ComputeZoom(const float scale, const Axis axis); // scale in [0, +inf]
        void ComputePosition(const Anchor xAnchor, const Anchor yAnchor); // Must be called after ComputeZoom
        void UsePaddingOnPosition(const float xPadding, const float yPadding);
        void DrawTexture() const override; 
        void UpdatePosition(); // Update position on current UiElement and each children
        void SetLocalPosition(const ScreenPosition localPosition); // To move a UiElement, use this function, and not ScreenDrawable::SetScreenPosition()
        void AddLocalPosition(const ScreenPosition padding);
};

class UiTextElement : public UiElement
{
    private:
        std::string m_text;
        
        FontController& m_fontController; // Should not be here ?
        SDL_Color m_textColor;
        // Texture that is generated by a UiTextElement is in TextureController::m_textures
        FontKey m_fontKey; // Should not be here ?
        int m_maxWidth;

    public:
        UiTextElement(FontController& fontController, TextureController& textureController, const UiKey& key, 
            const std::string& fontFilepath, const SDL_Color color=SDL_Color{0,0,0,255});
        ~UiTextElement();

        void SetText(const std::string& text);
        void GenerateText();
        void SetMaxWidth(const float amount);

        void ComputeFinal() override;
};